### ISSUE TITLE
Feature request: integrate 'info' variable into compressed output

### ISSUE THREAD

**Issue by street-grease-coder** [NeuroJSON/zmat#6]
Just an idea, but I used the CompressLib (https://mathworks.com/matlabcentral/fileexchange/25656-compression-routines) to append the 'info' variable to the main output, because then it's a bit easier to store a single file on disk. 

Workflow is along the lines of:  load/generate data => compress in MATLAB using zmat => save to disk (as uint8) => load from disk directly into ram => decompress

Thanks for the work

**Comment by fangq** [comment]
if you prefer to store `info` along side with your compressed buffer, you can create a struct or cell array to combine the outputs into a single variable after calling zmat. I don't see a benefit for zmat to merge the output itself.

closing for now.
